// <auto-generated />
using System;
using LovatoOpticalApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LovatoOpticalApp.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lovato")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LovatoOpticalApp.Core.CrystalOrderWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bridge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Horizontal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("MajorDiagonal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mounting")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OD_ADD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OD_AXIS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OD_CIL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OD_DNP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OD_ESF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OD_HEIGHT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OI_ADD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OI_AXIS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OI_CIL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OI_DNP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OI_ESF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OI_HEIGHT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PanoramicAngle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PantoscopicAngle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("TreatmentNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vertical")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CrystalOrderWorks", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Accessory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Accessories", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Crystal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Crystals", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CiRuc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Discounts.DiscountByFixedAmount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FixedAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DiscountByFixedAmounts", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Discounts.DiscountByPercentage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DiscountByPercentages", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Frame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FrameType")
                        .HasColumnType("integer");

                    b.Property<int>("Material")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Frames", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CrystalLeftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrystalOrderWorkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CrystalRightId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FrameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CrystalLeftId");

                    b.HasIndex("CrystalOrderWorkId");

                    b.HasIndex("CrystalRightId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FrameId");

                    b.ToTable("Orders", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Payments.CashPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AmountReceived")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CashPayments", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Payments.CreditCardPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CardBrand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Installments")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CreditCardPayments", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Payments.DebitCardPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastFourDigits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DebitCardPayments", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Payments.PaymentProof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PaymentProofs", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Payments.TransferPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProofId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProofId");

                    b.ToTable("TransferPayments", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adicion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Optometrist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PrescriptionIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VC_OD_CIL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VC_OD_EJE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VC_OD_ESF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VC_OI_CIL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VC_OI_EJE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VC_OI_ESF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VL_OD_CIL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VL_OD_EJE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VL_OD_ESF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VL_OI_CIL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VL_OI_EJE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VL_OI_ESF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Recipes", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Users", "lovato");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Invoice", b =>
                {
                    b.HasOne("LovatoOpticalApp.Core.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Order", b =>
                {
                    b.HasOne("LovatoOpticalApp.Core.Entities.Crystal", "CrystalLeft")
                        .WithMany()
                        .HasForeignKey("CrystalLeftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LovatoOpticalApp.Core.CrystalOrderWork", "CrystalOrderWork")
                        .WithMany()
                        .HasForeignKey("CrystalOrderWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LovatoOpticalApp.Core.Entities.Crystal", "CrystalRight")
                        .WithMany()
                        .HasForeignKey("CrystalRightId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LovatoOpticalApp.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LovatoOpticalApp.Core.Entities.Frame", "Frame")
                        .WithMany()
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CrystalLeft");

                    b.Navigation("CrystalOrderWork");

                    b.Navigation("CrystalRight");

                    b.Navigation("Customer");

                    b.Navigation("Frame");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Payments.TransferPayment", b =>
                {
                    b.HasOne("LovatoOpticalApp.Core.Entities.Payments.PaymentProof", "Proof")
                        .WithMany()
                        .HasForeignKey("ProofId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proof");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Recipe", b =>
                {
                    b.HasOne("LovatoOpticalApp.Core.Entities.Customer", "Customer")
                        .WithMany("Recipes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LovatoOpticalApp.Core.Entities.Customer", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
